/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmpenhoController;
import javax.swing.JOptionPane;
import model.Empenho;
import model.Fornecedor;
import util.DateTimeUtil;



/**
 *
 * @author secinfor-04
 */
public class EmpenhoEditView extends javax.swing.JFrame {

    private  Fornecedor adicionado = Fornecedor.getInstacia();
    private Empenho empenho = new Empenho();
    
    static EmpenhoEditView instancia = null;  
      
     public static EmpenhoEditView getInstacia(){
       if(  instancia == null){
         return instancia = new EmpenhoEditView();
         } else{ 
         return instancia;
       }
     }
    public static EmpenhoEditView Instacia(){
       
         return instancia = new EmpenhoEditView();
         
     }
     
    public EmpenhoEditView(Empenho empenho) {
        initComponents();
        jtSaldo.setEditable(false);
        
        jtFornecedor.setEditable(false);
        
      
        jtCNPJ.setEditable(false);
        
        this.empenho = empenho;
        this.adicionado = empenho.getIdFornecedor();
        
        if(empenho.getSaldo()!= empenho.getValor()){
             
            jbIncluirFornecedor.setEnabled(false);
          jbGravar.setEnabled(false);
          
            carregaDados(empenho);
          JOptionPane.showMessageDialog(rootPane, "Empenho já utilizado impossivel edição!!!!", null, 2);
             
             
             
        }else{
          jtNumero.setEditable(true);
          
          jtfData.setEditable(true);
          jtValor.setEditable(true);
          carregaDados(empenho); 
        }
        
        
    }
    
    /**
     * Creates new form EmpenhoEditView
     */
    public EmpenhoEditView() {
        initComponents();
       
         jtSaldo.setEditable(false);
        
        jtFornecedor.setEditable(false);
       
        
        jtCNPJ.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jtFornecedor = new javax.swing.JTextField();
        jtCNPJ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfData = new javax.swing.JFormattedTextField();
        jbGravar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbIncluirFornecedor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlCadEmpenho = new javax.swing.JLabel();
        jtValor = new javax.swing.JFormattedTextField();
        jtSaldo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de empenho");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jLabel1.setText("Número:");

        jLabel2.setText("Fornecedor:");

        jLabel3.setText("CNPJ:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Saldo:");

        jLabel6.setText("Data:");

        jtfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbIncluirFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add (2).png"))); // NOI18N
        jbIncluirFornecedor.setText("Incluir Fornecedor");
        jbIncluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirFornecedorActionPerformed(evt);
            }
        });

        jlCadEmpenho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCadEmpenho.setText("Cadastro de Empenho ");

        jtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });

        jtSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbIncluirFornecedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlCadEmpenho))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCadEmpenho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIncluirFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGravar)
                    .addComponent(jbSair))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(478, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbIncluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirFornecedorActionPerformed
        // TODO add your handling code here:
        
   FornecedorSearchView janela = new FornecedorSearchView("");
           janela.setVisible(true);
       
        
        
    }//GEN-LAST:event_jbIncluirFornecedorActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
   
        
   
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        // TODO add your handling code here:
       EmpenhoController empenhoController = EmpenhoController.getInstacia();
    if(validaCaracteres()==null) {   
    if(campoObrigatorio()== null){   
        DateTimeUtil dataUtil = DateTimeUtil.getInstancia();
        empenho.setNumero(jtNumero.getText());
        empenho.setData(dataUtil.parse("dd/MM/YYYY", jtfData.getText()));
        empenho.setValor(Float.parseFloat(jtValor.getText().replace(",", ".")));
        empenho.setSaldo(Float.parseFloat(jtSaldo.getText().replace(",", ".")));
        empenho.setIdFornecedor(adicionado);
    
    if(empenhoController.existir(empenho)||empenho.getId()!=null){
    if(empenhoController.persistir(empenho)){
          
          JOptionPane.showMessageDialog(null, "Empenho Gravado Com sucesso!", null, 1);
          
          this.dispose();
      }else{
          
          JOptionPane.showMessageDialog(null, "Falha ao Salvar Empenho!!", null, 2);
      }
    }else{
        
        JOptionPane.showMessageDialog(null, "Empenho já Cadastrado!!", null, 2);
        
    }
    }else{
        
        JOptionPane.showMessageDialog(null, campoObrigatorio(), null, 2);
    }  
    }else{
        
        JOptionPane.showMessageDialog(null, validaCaracteres(), null, 2);
    }
    



    }//GEN-LAST:event_jbGravarActionPerformed

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
   jtSaldo.setText(jtValor.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorFocusLost

    private void jtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpenhoEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpenhoEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpenhoEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpenhoEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpenhoEditView().setVisible(true);
            }
        });
    }
    
    /**
     *
     */
    
    //carrega dados para alterar 
    private void carregaDados(Empenho empenho){
       
        DateTimeUtil dataUtil = DateTimeUtil.getInstancia();
        
        
      jtFornecedor.setText(empenho.getIdFornecedor().getNome());
      jtCNPJ.setText(empenho.getIdFornecedor().getCnpj());
      jtfData.setText( dataUtil.parseDate(empenho.getData()));
      jtValor.setText(Float.toString(empenho.getValor()).replace(".", ","));
      jtSaldo.setText(Float.toString(empenho.getSaldo()).replace(".", ","));
      jtNumero.setText(empenho.getNumero());
      
        
        
        
    }
    
    
    public void adicionarFornecedor(Fornecedor fornecedor){
        
       adicionado = fornecedor; 
        jtFornecedor.setText(adicionado.getNome());
        jtCNPJ.setText(adicionado.getCnpj());
        
          }
    
    
    private String campoObrigatorio(){
       
        String vazio = "Campo Obrigatorio Em Branco : ";
       boolean msg = false;
       
        if(jtValor.getText().equals("")){
          
            vazio = vazio + "\n Valor ";
            
        msg = true; 
        }
        if(jtfData.getText().equals("")){
          
            vazio = vazio + "\n Data ";
            
          msg = true;
        }
      
        if(jtCNPJ.getText().equals("")){
          
            vazio = vazio + " \n CNPJ ";
            
         msg = true; 
        }
        if(jtNumero.getText().equals("")){
          
            vazio = vazio + " \n Numero ";
            
         msg = true; 
        }
             
        if(msg){
            
            return vazio;
        }else{
        
        return vazio = null;
    }
       }
    
    //valida campos com caracteres minimos
    private String validaCaracteres(){
       
        String vazio = "Campos com poucos caracteres : ";
       boolean msg = false;
                     
        if(jtNumero.getText().length()<3){
          
            vazio = vazio + " \n Numero ";
            
         msg = true; 
        }
             
        if(msg){
            
            return vazio;
        }else{
        
        return vazio = null;
    }
       }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbIncluirFornecedor;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlCadEmpenho;
    private javax.swing.JTextField jtCNPJ;
    private javax.swing.JTextField jtFornecedor;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JFormattedTextField jtSaldo;
    private javax.swing.JFormattedTextField jtValor;
    private javax.swing.JFormattedTextField jtfData;
    // End of variables declaration//GEN-END:variables
}
