/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import dao.MontadoraDAO;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Montadora;
import model.Produto;

/**
 *
 * @author secinfor-04
 */
public class ProdutoEditView extends javax.swing.JFrame {

   private Produto produto = Produto.getInstacia();
   private List  montadoras;
    
    /**
     * Creates new form ProdutoEditView
     */
    public ProdutoEditView(Produto produto) {
        initComponents();
        carregaComboBox();
        carregaDados(produto);
        this.produto = produto;
        
    }
    
    
    public ProdutoEditView() {
        initComponents();
        carregaComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNumeroPeca = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jtLocalizacao = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbMontadora = new javax.swing.JComboBox();
        jbGravar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jtfValor = new javax.swing.JFormattedTextField();
        try{
            MaskFormatter moeda = new MaskFormatter("#######,##");
            moeda.setPlaceholderCharacter('_');
            jtfValor = new JFormattedTextField(moeda);
        }catch(Exception e){

        }

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);

        jLabel1.setText("Número Peça:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Localização:");

        jLabel4.setText("Quantidade:");

        jLabel6.setText("Montadora:");

        jLabel7.setText("Valor:");

        jcbMontadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Item" }));

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Success.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cadastro de Produtos");

        jtfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfValor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbMontadora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtNumeroPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumeroPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGravar)
                    .addComponent(jbSair))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(395, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    
        this.dispose();        
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        // TODO add your handling code here:
    
           
    if(campoObrigatorio()==null){
      
     
     produto.setIdMontadora(selecionada());
     produto.setDescricao(jtDescricao.getText());
     produto.setLocalizacao(jtLocalizacao.getText());
     produto.setNumeroPeca(jtNumeroPeca.getText());
     produto.setQuantidade(Integer.parseInt(jtQuantidade.getText()));
     produto.setValor(Float.parseFloat(jtfValor.getText().replace(",", ".")));
    
     
           
      ProdutoController produtoController = ProdutoController.getInstacia();
      
      if(produtoController.persistir(produto)){
          
          JOptionPane.showMessageDialog(null, "Produto Gravado Com sucesso!", null, 1);
          
          this.dispose();
      }else{
          
          JOptionPane.showMessageDialog(null, "Falha ao Salvar Produto!!", null, 2);
      }
        
     }else{  
         
        JOptionPane.showMessageDialog(null, campoObrigatorio(), null, 2); 
     }    
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoEditView().setVisible(true);
            }
        });
    }
    
    // metodo que valida Campo em Branco
    private String campoObrigatorio(){
       
        String vazio = "Campo Obrigatorio Em Branco ou Não Selecionado: ";
       boolean msg = false;
       
        if(jtNumeroPeca.getText().equals("")){
          
            vazio = vazio + "\n Numero da Peça ";
            
        msg = true; 
        }
        if(jtDescricao.getText().equals("")){
          
            vazio = vazio + "\n Descrição ";
            
          msg = true;
        }
        if(jtLocalizacao.getText().equals("")){
          
            vazio = vazio + "\n Localização ";
            
          msg = true;
        }
        if(jtQuantidade.getText().equals("")){
          
            vazio = vazio + "\n Quantidade ";
            
          msg = true;
        }
        if(jtfValor.getText().equals("")){
          
            vazio = vazio + "\n Valor ";
            
          msg = true;
        }
        
        if(jcbMontadora.getSelectedItem().equals("Selecione um item")){
          
            vazio = vazio + " \n Montadora ";
            
         msg = true; 
        }
             
        if(msg){
        
            return vazio;
        }else{
        
        return vazio = null;
    }
       }
    //carrega dados para alterar 
    private void carregaDados(Produto produto){
       
     
      
        jtNumeroPeca.setText(produto.getNumeroPeca());
        jtDescricao.setText(produto.getDescricao());
        jtLocalizacao.setText(produto.getLocalizacao());
        jtQuantidade.setText(Integer.toString(produto.getQuantidade()));
        jtfValor.setText(Float.toString(produto.getValor()).replace(".", ","));
        jcbMontadora.setSelectedItem(produto.getIdMontadora().getNome());
        
    }
    
    
    private void carregaComboBox(){
      MontadoraDAO montadoraDAO = MontadoraDAO.getInstacia();
      montadoras =  montadoraDAO.listaTodas();
    
      for(int i = 0; i<montadoras.size();i++){
        
          Montadora montadora = (Montadora) montadoras.get(i);
          
       jcbMontadora.addItem(montadora.getNome());
         
    
       }
      
  
    }
    
    private Montadora selecionada(){
        
     Montadora montadora = Montadora.getInstacia();   
       
     montadora = (Montadora) montadoras.get(jcbMontadora.getSelectedIndex()-1);
         
         
        return montadora; 
     } 
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbSair;
    private javax.swing.JComboBox jcbMontadora;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtLocalizacao;
    private javax.swing.JTextField jtNumeroPeca;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JFormattedTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
