/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import util.DateTimeUtil;
import util.Imprimir;

/**
 *
 * @author secinfor-04
 */
public class RelatorioPeriodoView extends javax.swing.JFrame {
private int relatorio;
    /**
     * Creates new form RelatorioPeriodoView
     */
    public RelatorioPeriodoView() {
        initComponents();
    }
public RelatorioPeriodoView(int relatorio) {
        initComponents();
        this.relatorio = relatorio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbGerar = new javax.swing.JButton();
        jtDataInicio = new javax.swing.JFormattedTextField();
        jtDataFim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Data Inicio:");

        jLabel2.setText("Data Final:");

        jbGerar.setText("Gerar");
        jbGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarActionPerformed(evt);
            }
        });

        jtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGerar)
                        .addContainerGap(221, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDataInicio)
                            .addComponent(jtDataFim))
                        .addGap(145, 145, 145))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbGerar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarActionPerformed
        // TODO add your handling code here:
      Date dataFim ;
      Date dataInicio;  
      
      
    Imprimir relat = new Imprimir();
        DateTimeUtil dataUtil = DateTimeUtil.getInstancia();
        HashMap<String,Object> map = new HashMap<String,Object>();
        
        
        dataInicio = dataUtil.parseDateException(jtDataInicio.getText());
     dataFim = dataUtil.parseDateException(jtDataFim.getText());
        switch(relatorio){
            
           case 2:{
                
               
               
             
               // falta colocar um joption pane 
             
               
               map.put("dataInicio", dataInicio);
               map.put("dataFim", dataFim);
               
               
               try {
          
          relat.imprimeRelatorioEntradaPorPeriodo(map);
          this.dispose();
        } catch (JRException ex) {
           JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        }    
               
                break;
            } 
            
             case 9:{
                
               map.put("dataInicio", dataInicio);
               map.put("dataFim", dataFim);     
                 
                 
                 
                 try {
          
          relat.imprimeRelatorioProdutoPorPeriodo(map);
          this.dispose();
       } catch (JRException ex) {
           JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        }   
                 
                break;
            } 
         case 12:{
                
                           
               map.put("dataInicio", dataInicio);
               map.put("dataFim", dataFim); 
                
                try {
          
          relat.imprimeRelatorioSaidaPorPeriodo(map);
          this.dispose();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
            Logger.getLogger(SRMView.class.getName()).log(Level.SEVERE, null, ex);
        }    
                
                break;
            } 
            default:{
                
               JOptionPane.showMessageDialog(rootPane, relat, "Falha ao Gerar Relatório!", 2);
                
                
                break;
            }
                
        }    
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPeriodoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPeriodoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPeriodoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPeriodoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPeriodoView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbGerar;
    private javax.swing.JFormattedTextField jtDataFim;
    private javax.swing.JFormattedTextField jtDataInicio;
    // End of variables declaration//GEN-END:variables
}
