/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItensSaidaController;
import controller.ProdutoController;
import controller.SaidaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItensSaida;
import model.Mecanico;
import model.OrdemDeServico;
import model.Produto;
import model.Saida;
import util.DateTimeUtil;

/**
 *
 * @author secinfor-04
 */
public class SaidaEditView extends javax.swing.JFrame {

    
    private ItensSaida itensSaida = ItensSaida.getInstacia();
    private Saida saida = Saida.getInstacia();
    private Produto produtoAdd = Produto.getInstacia();
    private Mecanico mecanicoAdd;
    private OrdemDeServico ordemDeServicoAdd;
    private DateTimeUtil dataUtil = DateTimeUtil.getInstancia();
    
    
    
    static SaidaEditView instancia = null;  
      
     public static SaidaEditView getInstacia(){
       if(  instancia == null){
         return instancia = new SaidaEditView();
         } else{ 
         return instancia;
       }
     }
     
     
     
     public static SaidaEditView getInstacia(Saida saida){
       if(  instancia == null){
         return instancia = new SaidaEditView(saida);
         } else{ 
         return instancia;
       }
     }
    /**
     * Creates new form EntradaEditView
     */
     
     
    public SaidaEditView(Saida saida) {
        
        initComponents();
   
    jtMecanico.setEditable(false);
     jtOrdemDeServico.setEditable(false);
    jtOM.setEditable(false);
    jtfData.setEditable(false);
    jtNumero.setEditable(false);
    this.saida = saida ;
    ordemDeServicoAdd = saida.getIdOrdemDeServico();
    mecanicoAdd = saida.getIdMecanico();
    carregaTabela();
    jbIncluirItem.setVisible(false);   
    } 
    
    
    
    public SaidaEditView() {
        initComponents();
       jtMecanico.setEditable(false);
     jtOrdemDeServico.setEditable(false);
    jtOM.setEditable(false);
    jtfData.setEditable(false);
    jtNumero.setEditable(false);
        
    jtfData.setText(dataUtil.parse("dd/MM/YYYY", dataUtil.getCurrentDateTime()));
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jtMecanico = new javax.swing.JTextField();
        jtOrdemDeServico = new javax.swing.JTextField();
        jtOM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObservacoes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jtfData = new javax.swing.JFormattedTextField();
        jbIncluirMecanico = new javax.swing.JButton();
        jbIncluirOS = new javax.swing.JButton();
        jbIncluirItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtItensSaida = new javax.swing.JTable();
        jbGravar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Saída");
        setResizable(false);

        jLabel1.setText("Número:");

        jLabel10.setText("Mecânico:");

        jLabel2.setText("Ordem de Serviço:");

        jLabel3.setText("OM:");

        jLabel4.setText("Observações:");

        jtaObservacoes.setColumns(20);
        jtaObservacoes.setRows(5);
        jScrollPane1.setViewportView(jtaObservacoes);

        jLabel5.setText("Data:");

        jbIncluirMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add (2).png"))); // NOI18N
        jbIncluirMecanico.setText("Incluir Mecânico");
        jbIncluirMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirMecanicoActionPerformed(evt);
            }
        });

        jbIncluirOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add (2).png"))); // NOI18N
        jbIncluirOS.setText("Incluir OS");
        jbIncluirOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirOSActionPerformed(evt);
            }
        });

        jbIncluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add (2).png"))); // NOI18N
        jbIncluirItem.setText("Incluir Item");
        jbIncluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirItemActionPerformed(evt);
            }
        });

        jtItensSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Peça", "Número Peça", "Descrição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtItensSaida);
        jtItensSaida.getColumnModel().getColumn(0).setResizable(false);
        jtItensSaida.getColumnModel().getColumn(0).setPreferredWidth(5);
        jtItensSaida.getColumnModel().getColumn(1).setResizable(false);
        jtItensSaida.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtItensSaida.getColumnModel().getColumn(2).setResizable(false);
        jtItensSaida.getColumnModel().getColumn(2).setPreferredWidth(50);
        jtItensSaida.getColumnModel().getColumn(3).setResizable(false);
        jtItensSaida.getColumnModel().getColumn(3).setPreferredWidth(5);

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Success.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cadastro de Saída");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(jtMecanico)
                                            .addComponent(jtOrdemDeServico)
                                            .addComponent(jtOM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfData))
                                            .addComponent(jbIncluirMecanico)
                                            .addComponent(jbIncluirOS)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(jbIncluirItem))))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIncluirMecanico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIncluirOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jbIncluirItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGravar)
                    .addComponent(jbSair))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(488, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbIncluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirItemActionPerformed
        // TODO add your handling code here:
     
     
     ProdutoSearchView janelaProduto = new ProdutoSearchView("saida");   
     janelaProduto.setVisible(true);    
       
        
        
    }//GEN-LAST:event_jbIncluirItemActionPerformed

    private void jbIncluirOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirOSActionPerformed
        // TODO add your handling code here:
        
        
     OrdemDeServicoSearchView janelaOrdemDeServico = new OrdemDeServicoSearchView("");   
     janelaOrdemDeServico.setVisible(true); 
        
        
        
    }//GEN-LAST:event_jbIncluirOSActionPerformed

    private void jbIncluirMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirMecanicoActionPerformed
        // TODO add your handling code here:
     
     MecanicoSearchView janelaMecanico = new MecanicoSearchView("");   
     janelaMecanico.setVisible(true);    
        
        
        
        
    }//GEN-LAST:event_jbIncluirMecanicoActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        // TODO add your handling code here:
        SaidaController saidaController = SaidaController.getInstacia();
        ProdutoController produtoController = ProdutoController.getInstacia();

        DateTimeUtil dataUtil = DateTimeUtil.getInstancia();
        ItensSaidaController itensSaidaController = ItensSaidaController.getInstacia();
        
        
        saida.setIdOrdemDeServico(ordemDeServicoAdd);
        saida.setData(dataUtil.parseDate(jtfData.getText()));
        saida.setIdMecanico(mecanicoAdd);
        saida.setObservacoes(jtaObservacoes.getText());
        saida.setData(dataUtil.parseDate(jtfData.getText()));
            
        
       List gravar = saidaController.persistir(saida);
      if(gravar.get(0)== true){
         if(jtNumero.getText().equals("")){
          saida = (Saida) gravar.get(1);
          jtNumero.setText(Long.toString(saida.getId()));
         }
      
       DefaultTableModel modelo = (DefaultTableModel) jtItensSaida.getModel();
     
       for(int i =0 ; i <=modelo.getRowCount()-1; i++){
       
           String id = (String) modelo.getValueAt(i, 0);
           
        produtoAdd.setId(Long.parseLong(id));
           
           
         itensSaida.setIdProduto(produtoAdd);
         itensSaida.setIdSaida(saida);
           
         itensSaidaController.persistir(itensSaida);
         produtoController.editaQuantidade(itensSaida);
           
       }
        
        JOptionPane.showMessageDialog(null, "Saída Gravado Com sucesso!", null, 1);
          
        this.dispose();  
             
        
       
      }else{
          
          
          
          JOptionPane.showMessageDialog(null, "Falha ao Salvar Saída!!", null, 2);
      }
        
        
        
        
        
        
    }//GEN-LAST:event_jbGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaEditView().setVisible(true);
            }
        });
    }
    
     //adiciona empenho a entrada
    public void adicionarOrdemDeServico(OrdemDeServico ordemDeServico){
        
       ordemDeServicoAdd = ordemDeServico; 
        jtOrdemDeServico.setText(ordemDeServicoAdd.getId().toString());
        jtOM.setText(ordemDeServicoAdd.getOm());
          
          }
    
    public void adicionarMecanico(Mecanico mecanico){
        
       mecanicoAdd = mecanico; 
        jtMecanico.setText(mecanicoAdd.getPosto() + " " + mecanicoAdd.getNomeGuerra());
        
          }
    
    public void adicionarProduto(Produto produto){
     
     String dado = JOptionPane.showInputDialog(rootPane, "informe a Quantidade", null);
      itensSaida.setQuantidade(Integer.parseInt(dado));
      itensSaida.setIdProduto(produto);
      DefaultTableModel modelo = (DefaultTableModel) jtItensSaida.getModel();
      modelo.addRow(new String[]{produto.getId().toString(), produto.getNumeroPeca(), produto.getDescricao(), Integer.toString(itensSaida.getQuantidade())});
    
    }
   
       
    private void carregaTabela(){
     List<ItensSaida> itensSaidaLista = new ArrayList();
      DefaultTableModel modelo = (DefaultTableModel) jtItensSaida.getModel();
    itensSaidaLista = (List) saida.getItensSaidaCollection();
     
    jtNumero.setText(saida.getId().toString());
    jtMecanico.setText(saida.getIdMecanico().getPosto() + " " + saida.getIdMecanico().getNomeGuerra());
    jtOM.setText(saida.getIdOrdemDeServico().getOm());
    jtaObservacoes.setText(saida.getObservacoes());
    jtfData.setText(dataUtil.parse("dd/MM/YYYY", saida.getData()));
    jtOrdemDeServico.setText(saida.getIdOrdemDeServico().getId().toString());
    
    
      
      
       for(int i = 0; i<itensSaidaLista.size();i++){
     itensSaida = itensSaidaLista.get(i);
  modelo.addRow(new String[]{itensSaida.getIdProduto().getId().toString(), itensSaida.getIdProduto().getNumeroPeca(), itensSaida.getIdProduto().getDescricao(), Integer.toString(itensSaida.getIdProduto().getQuantidade())});
            
       }
      
    }
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbIncluirItem;
    private javax.swing.JButton jbIncluirMecanico;
    private javax.swing.JButton jbIncluirOS;
    private javax.swing.JButton jbSair;
    private javax.swing.JTable jtItensSaida;
    private javax.swing.JTextField jtMecanico;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtOM;
    private javax.swing.JTextField jtOrdemDeServico;
    private javax.swing.JTextArea jtaObservacoes;
    private javax.swing.JFormattedTextField jtfData;
    // End of variables declaration//GEN-END:variables
}
