/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario; 


/**
 *
 * @author secinfor-04
 */
public class SRMView extends javax.swing.JFrame {

    Usuario usuario;

   public SRMView(Usuario usuario){
       initComponents();
       this.usuario = usuario;
    
    
    permissao(usuario);
   
   
   }

    /**
     * Creates new form SRMVeiw
     */
    public SRMView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorpo = new javax.swing.JPanel();
        jpRodape = new javax.swing.JPanel();
        jbEmp = new javax.swing.JButton();
        jbForn = new javax.swing.JButton();
        jbMec = new javax.swing.JButton();
        jbMont = new javax.swing.JButton();
        jbProd = new javax.swing.JButton();
        jbUsuario = new javax.swing.JButton();
        jtpPrincipal = new javax.swing.JTabbedPane();
        jpArquivo = new javax.swing.JPanel();
        jbLogout = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jpMov = new javax.swing.JPanel();
        jbCadEntrada = new javax.swing.JButton();
        jbCadSaida = new javax.swing.JButton();
        jbCadOS = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jpCad = new javax.swing.JPanel();
        jbCadEmp = new javax.swing.JButton();
        jbCadForn = new javax.swing.JButton();
        jbCadMec = new javax.swing.JButton();
        jbCadMont = new javax.swing.JButton();
        jbCadProd = new javax.swing.JButton();
        jbcadUsuaro = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jpRelat = new javax.swing.JPanel();
        jcbRelatorios = new javax.swing.JComboBox();
        jlRelat = new javax.swing.JLabel();
        jbAbrirRelat = new javax.swing.JButton();
        jpHelp = new javax.swing.JPanel();
        jbAjuda = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SRM Sistema de Reserva de Materiais");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jpCorpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpCorpoLayout = new javax.swing.GroupLayout(jpCorpo);
        jpCorpo.setLayout(jpCorpoLayout);
        jpCorpoLayout.setHorizontalGroup(
            jpCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpCorpoLayout.setVerticalGroup(
            jpCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jbEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coins_add.png"))); // NOI18N
        jbEmp.setToolTipText("Incluir empenho");
        jbEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmpActionPerformed(evt);
            }
        });

        jbForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry_add.png"))); // NOI18N
        jbForn.setToolTipText("Incluir fornecedor");
        jbForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornActionPerformed(evt);
            }
        });

        jbMec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        jbMec.setToolTipText("Incluir mecânico");
        jbMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMecActionPerformed(evt);
            }
        });

        jbMont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car_add.png"))); // NOI18N
        jbMont.setToolTipText("Incluir montadora");
        jbMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMontActionPerformed(evt);
            }
        });

        jbProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package_add.png"))); // NOI18N
        jbProd.setToolTipText("Incluir produto");
        jbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdActionPerformed(evt);
            }
        });

        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vcard_add.png"))); // NOI18N
        jbUsuario.setToolTipText("Incluir usuário");
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRodapeLayout = new javax.swing.GroupLayout(jpRodape);
        jpRodape.setLayout(jpRodapeLayout);
        jpRodapeLayout.setHorizontalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbForn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRodapeLayout.setVerticalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEmp)
                    .addComponent(jbForn)
                    .addComponent(jbMec)
                    .addComponent(jbMont)
                    .addComponent(jbProd)
                    .addComponent(jbUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_out.png"))); // NOI18N
        jbLogout.setText("Logout");

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSairMouseClicked(evt);
            }
        });
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpArquivoLayout = new javax.swing.GroupLayout(jpArquivo);
        jpArquivo.setLayout(jpArquivoLayout);
        jpArquivoLayout.setHorizontalGroup(
            jpArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jpArquivoLayout.setVerticalGroup(
            jpArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jbLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        jtpPrincipal.addTab("Arquivo", jpArquivo);

        jbCadEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/basket_put.png"))); // NOI18N
        jbCadEntrada.setText("Entrada");
        jbCadEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadEntradaActionPerformed(evt);
            }
        });

        jbCadSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/basket_remove.png"))); // NOI18N
        jbCadSaida.setText("Saída");
        jbCadSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadSaidaActionPerformed(evt);
            }
        });

        jbCadOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.png"))); // NOI18N
        jbCadOS.setText("Ordem de serviço");
        jbCadOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadOSActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpMovLayout = new javax.swing.GroupLayout(jpMov);
        jpMov.setLayout(jpMovLayout);
        jpMovLayout.setHorizontalGroup(
            jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadOS)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        jpMovLayout.setVerticalGroup(
            jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jbCadEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jbCadSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jbCadOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpPrincipal.addTab("Movimentação", jpMov);

        jbCadEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coins.png"))); // NOI18N
        jbCadEmp.setText("Empenho");
        jbCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadEmpActionPerformed(evt);
            }
        });

        jbCadForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry.png"))); // NOI18N
        jbCadForn.setText("Fornecedor");
        jbCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadFornActionPerformed(evt);
            }
        });

        jbCadMec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jbCadMec.setText("Mecânico");
        jbCadMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadMecActionPerformed(evt);
            }
        });

        jbCadMont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car.png"))); // NOI18N
        jbCadMont.setText("Montadora");
        jbCadMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadMontActionPerformed(evt);
            }
        });

        jbCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package.png"))); // NOI18N
        jbCadProd.setText("Produto");
        jbCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadProdActionPerformed(evt);
            }
        });

        jbcadUsuaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vcard.png"))); // NOI18N
        jbcadUsuaro.setText("Usuário");
        jbcadUsuaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcadUsuaroActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpCadLayout = new javax.swing.GroupLayout(jpCad);
        jpCad.setLayout(jpCadLayout);
        jpCadLayout.setHorizontalGroup(
            jpCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadForn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadMec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadMont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbcadUsuaro)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jpCadLayout.setVerticalGroup(
            jpCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jbcadUsuaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(jbCadForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator6)
                    .addComponent(jbCadMec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addComponent(jbCadMont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addComponent(jbCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator9))
                .addContainerGap())
        );

        jtpPrincipal.addTab("Cadastro", jpCad);

        jcbRelatorios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Crédito Detalhado Empenho", "Entrada Produto 'B'", "Entrada Por Período", "Estoque Geral", "Empenho", "Fornecedores", "Montadora", "Mecânico", "Ordem de Serviço", "Produto Por Período", "Produtos Por Saída", "Produtos Por Montadora", "Saída Por Período" }));

        jlRelat.setText("Selecione o relatório:");

        jbAbrirRelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Folder (2).png"))); // NOI18N
        jbAbrirRelat.setToolTipText("Abrir");
        jbAbrirRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirRelatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRelatLayout = new javax.swing.GroupLayout(jpRelat);
        jpRelat.setLayout(jpRelatLayout);
        jpRelatLayout.setHorizontalGroup(
            jpRelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRelatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRelat)
                .addGap(12, 12, 12)
                .addComponent(jcbRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAbrirRelat)
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jpRelatLayout.setVerticalGroup(
            jpRelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRelatLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpRelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRelat)
                    .addComponent(jbAbrirRelat))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtpPrincipal.addTab("Relatório", jpRelat);

        jbAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jbAjuda.setText("Ajuda");

        jbSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Display.png"))); // NOI18N
        jbSobre.setText("Sobre");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpHelpLayout = new javax.swing.GroupLayout(jpHelp);
        jpHelp.setLayout(jpHelpLayout);
        jpHelpLayout.setHorizontalGroup(
            jpHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSobre)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        jpHelpLayout.setVerticalGroup(
            jpHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addComponent(jbSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpPrincipal.addTab("Help", jpHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(919, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairMouseClicked

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCadEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadEntradaActionPerformed
        // TODO add your handling code here:
        EntradaSearchView janelaEntrada = new EntradaSearchView(usuario);
        janelaEntrada.setVisible(true);
    }//GEN-LAST:event_jbCadEntradaActionPerformed

    private void jbCadSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadSaidaActionPerformed
        // TODO add your handling code here:
        SaidaSearchView janelaSaida = new SaidaSearchView(usuario);
        janelaSaida.setVisible(true);
    }//GEN-LAST:event_jbCadSaidaActionPerformed

    private void jbCadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadOSActionPerformed
        // TODO add your handling code here:
        OrdemDeServicoSearchView janelaOrdemDeServico = new OrdemDeServicoSearchView(usuario);
        janelaOrdemDeServico.setVisible(true);
    }//GEN-LAST:event_jbCadOSActionPerformed

    private void jbCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadEmpActionPerformed
        // TODO add your handling code here:
        EmpenhoSearchView janelaEmpenho = new EmpenhoSearchView(usuario);
        janelaEmpenho.setVisible(true);
    }//GEN-LAST:event_jbCadEmpActionPerformed

    private void jbCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadFornActionPerformed
        // TODO add your handling code here:
        FornecedorSearchView janelaFornecedor = new FornecedorSearchView(usuario);
        janelaFornecedor.setVisible(true);
    }//GEN-LAST:event_jbCadFornActionPerformed

    private void jbCadMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadMecActionPerformed
        // TODO add your handling code here:
        MecanicoSearchView janelaMecanico = new MecanicoSearchView(usuario);
        janelaMecanico.setVisible(true);
    }//GEN-LAST:event_jbCadMecActionPerformed

    private void jbCadMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadMontActionPerformed
        // TODO add your handling code here:
        MontadoraSearchView janelaMontadora = new MontadoraSearchView(usuario);
        janelaMontadora.setVisible(true);
    }//GEN-LAST:event_jbCadMontActionPerformed

    private void jbCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadProdActionPerformed
        // TODO add your handling code here:
        ProdutoSearchView janelaProduto = new ProdutoSearchView(usuario);
        janelaProduto.setVisible(true);
    }//GEN-LAST:event_jbCadProdActionPerformed

    private void jbcadUsuaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcadUsuaroActionPerformed
        // TODO add your handling code here:
        UsuarioSearchView janelaUsuario = new UsuarioSearchView(usuario);
        janelaUsuario.setVisible(true);
    }//GEN-LAST:event_jbcadUsuaroActionPerformed

    private void jbEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmpActionPerformed
        // TODO add your handling code here:
        EmpenhoEditView janelaEmpenho = new EmpenhoEditView();
        janelaEmpenho.setVisible(true);
        
    }//GEN-LAST:event_jbEmpActionPerformed

    private void jbFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornActionPerformed
        // TODO add your handling code here:
        FornecedorEditView janelaFornecedor = new FornecedorEditView();
        janelaFornecedor.setVisible(true);
    }//GEN-LAST:event_jbFornActionPerformed

    private void jbMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMecActionPerformed
        // TODO add your handling code here:
        MecanicoEditView janelaMecanico = new MecanicoEditView();
        janelaMecanico.setVisible(true);
    }//GEN-LAST:event_jbMecActionPerformed

    private void jbMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMontActionPerformed
        // TODO add your handling code here:
        MontadoraEditView janelaMontadora = new MontadoraEditView();
        janelaMontadora.setVisible(true);
    }//GEN-LAST:event_jbMontActionPerformed

    private void jbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdActionPerformed
        // TODO add your handling code here:
        ProdutoEditView janelaProduto = new ProdutoEditView();
        janelaProduto.setVisible(true);
    }//GEN-LAST:event_jbProdActionPerformed

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioEditView janelaUsuario = new UsuarioEditView();
        janelaUsuario.setVisible(true);
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void jbAbrirRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirRelatActionPerformed
        // TODO add your handling code here:       
       
        
        // fazer um if selecteditem da combo, para abrir cada tela
    }//GEN-LAST:event_jbAbrirRelatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
  
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRMView().setVisible(true);
            }
        });
    }
    private void permissao(Usuario usuario){      
        switch (usuario.getPerfil()){
       case "Garagem"   :{
       
       jbCadEmp.setVisible(false);
       jbCadSaida.setVisible(false);    
       jbCadEmp.setVisible(false);
       jbCadMont.setVisible(false);
       jbCadProd.setVisible(false);
       jbCadForn.setVisible(false);
       jcbRelatorios.setVisible(false);
       
               
       break;} 
       case "Estoquista" : {      
         
       jbCadOS.setVisible(false);
       jbCadMec.setVisible(false);
       jcbRelatorios.setVisible(false);       
       jbCadForn.setVisible(false);
       jbCadEmp.setVisible(false);     
        
       break;}
       default :{
       
       
       }    
   }
  } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbAbrirRelat;
    private javax.swing.JButton jbAjuda;
    private javax.swing.JButton jbCadEmp;
    private javax.swing.JButton jbCadEntrada;
    private javax.swing.JButton jbCadForn;
    private javax.swing.JButton jbCadMec;
    private javax.swing.JButton jbCadMont;
    private javax.swing.JButton jbCadOS;
    private javax.swing.JButton jbCadProd;
    private javax.swing.JButton jbCadSaida;
    private javax.swing.JButton jbEmp;
    private javax.swing.JButton jbForn;
    private javax.swing.JButton jbLogout;
    private javax.swing.JButton jbMec;
    private javax.swing.JButton jbMont;
    private javax.swing.JButton jbProd;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSobre;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JButton jbcadUsuaro;
    private javax.swing.JComboBox jcbRelatorios;
    private javax.swing.JLabel jlRelat;
    private javax.swing.JPanel jpArquivo;
    private javax.swing.JPanel jpCad;
    private javax.swing.JPanel jpCorpo;
    private javax.swing.JPanel jpHelp;
    private javax.swing.JPanel jpMov;
    private javax.swing.JPanel jpRelat;
    private javax.swing.JPanel jpRodape;
    private javax.swing.JTabbedPane jtpPrincipal;
    // End of variables declaration//GEN-END:variables
}
